
export const FLAGS = {
  MEX: require('../assets/jogos/mexico.png'),
  RSA: require('../assets/jogos/south africa.png'),
  KOR: require('../assets/jogos/south korea.png'),
  CZE: require('../assets/jogos/czech republic.png'),
  CAN: require('../assets/jogos/canada.png'),
  BIH: require('../assets/jogos/bosnia.png'),
  USA: require('../assets/jogos/usa.png'),
  PAR: require('../assets/jogos/paraguay.png'),
  HAI: require('../assets/jogos/haiti.png'),
  SCO: require('../assets/jogos/scotland.png'),
  AUS: require('../assets/jogos/australia.png'),
  TUR: require('../assets/jogos/turkey.png'),
  BRA: require('../assets/jogos/brazil.png'),
  MAR: require('../assets/jogos/morocco.png'),
  QAT: require('../assets/jogos/qatar.png'),
  SUI: require('../assets/jogos/switzerland.png'),
  CIV: require('../assets/jogos/ivory coast.png'),
  ECU: require('../assets/jogos/ecuador.png'),
  GER: require('../assets/jogos/germany.png'),
  CUW: require('../assets/jogos/curacao.png'),
  NED: require('../assets/jogos/netherlands.png'),
  JPN: require('../assets/jogos/japan.png'),
  SWE: require('../assets/jogos/sweden.png'),
  TUN: require('../assets/jogos/tunisia.png'),
  KSA: require('../assets/jogos/saudi arabia.png'),
  URU: require('../assets/jogos/uruguay.png'),
  ESP: require('../assets/jogos/spain.png'),
  CPV: require('../assets/jogos/cape verde.png'),
  IRN: require('../assets/jogos/iran.png'),
  NZL: require('../assets/jogos/new zealand.png'),
  BEL: require('../assets/jogos/belgium.png'),
  EGY: require('../assets/jogos/egypt.png'),
  FRA: require('../assets/jogos/france.png'),
  SEN: require('../assets/jogos/senegal.png'),
  IRQ: require('../assets/jogos/iraq.png'),
  NOR: require('../assets/jogos/norway.png'),
  ARG: require('../assets/jogos/argentina.png'),
  ALG: require('../assets/jogos/algeria.png'),
  AUT: require('../assets/jogos/austria.png'),
  JOR: require('../assets/jogos/jordan.png'),
  GHA: require('../assets/jogos/ghana.png'),
  PAN: require('../assets/jogos/panama.png'),
  ENG: require('../assets/jogos/england.png'),
  CRO: require('../assets/jogos/croatia.png'),
  POR: require('../assets/jogos/portugal.png'),
  COD: require('../assets/jogos/dr congo.png'),
  UZB: require('../assets/jogos/uzbekistan.png'),
  COL: require('../assets/jogos/colombia.png'),
};